var chartData = {
    "labels": ["Shane Warne", "Sachin Tendulkar", "Jacques Kallis", "Adam Gilchrist", "Brian Lara", "Glenn McGrath", "Alistair Cook", "Kumar Sangakkara", "Ricky Ponting", "Wasim Akram", "James Anderson", "Muttiah Muralitharan", "Mathew Hayden", "AB De Villiers", "Viv Richards", "Dale Steyn", "Andrew Flintoff", "Virat Kohli", "Curtly Ambrose", "Hashim Amla", "Malcolm Marshall", "Mitchell Johnson", "Joe Root", "Garfield Sobers", "Virender Sehwag", "Stuart Broad", "Graeme Swann", "Kevin Pietersen", "Marcus Trescothick", "Steve Waugh", "Shoaib Akhtar", "Rahul Dravid", "Imran Khan", "Ben Stokes", "Brendon McCullum", "Ian Botham", "Graeme Smith", "MS Dhoni", "Richard Hadlee", "Mahela Jayawardene", "Justin Langer", "Gordon Greenidge", "Graham Gooch", "David Warner", "Brett Lee", "Chris Rogers", "Chris Gayle", "Dennis Lillee", "Barry Richards", "Waqar Younis", "Sunil Gavaskar", "Darren Gough", "Darren Lehmann", "Desmond Haynes", "Don Bradman", "Alan Knott", "Aravinda De Silva", "Charlotte Edwards", "Allan Donald", "Adam Voges", "James Hildreth", "Mitchell Starc", "Meg Lanning", "Michael Clarke", "Murali Karthik", "Shivnarine Chanderpaul", "Rohit Sharma", "Robert Key", "Saeed Ajmal", "Sam Robson", "Morne Morkel", "Mohammad Amir", "Michael Holding", "Jack Hobbs", "Mark Ramprakash", "Martin Crowe", "Jos Buttler", "Kagiso Rabada", "Abdul Qadir", "Andre Adams", "Andrew Symonds", "Andy Roberts", "Anil Kumble", "Cathryn Fitzpatrick", "Chaminda Vaas", "Chris Read", "David Masters", "Daniel Vettori", "Harbhajan Singh", "Ian Chappell", "Ian Bell", "Steve Harmison", "Tim Murtagh", "Vernon Philander", "Yasir Arafat", "Yasir Shah", "Rangana Herath", "Tim Southee", "Trent Boult", "Steven Davies", "Wahab Riaz", "Steve Smith", "Stephen Fleming", "Steve Finn", "Tim Bresnan", "Tim Linley", "Ian Bishop", "Inzamam-Ul_Haq", "Ian Healy", "Ian Shrubsole", "Graham Napier", "Graham Onions", "Greg Chappell", "H. D. Ackerman", "Hanif Mohammad", "Darren Stevens", "David Hussey", "Dwayne Leverock", "Gary Ballance", "Geoffry Boycott", "Geraint Jones", "Daien Martyn", "Chris Woakes", "Claire Taylor", "Claude Henderson", "Colin Cowdrey", "Corey Collymore", "Courtney Walsh", "Chris Cairns", "Andy Caddick", "Andrew Strauss", "Abdur Rehman", "Adam Lyth", "Adil Rashid", "Akbar Ansari", "Allan Border", "Kane Williamson", "Karen Bolton", "Katherine Brunt", "Lance Klusner", "Lasith Malinga", "Lisa Keightly", "Josh Hazlewood", "Joel Garnder", "Javed Miandad", "James Foster", "Matt Prior", "Matt Walker", "Mark Ealham", "Michael Hussey", "Michael Slater", "Michael Vaughan", "Michael Di Venuto", "Moeen Ali", "Moises Henriques", "Rashid Khan", "Rashid Latif", "Nathan Astle", "Nick Browne", "Owais Shah", "Pat Cummins", "Paul Nixon", "Pragyan Ojha", "Quinton De Kock", "Saqlain Mushtaq", "Sarah Taylor", "Shane Bond", "Shaun Pollock", "Saeed Anwar", "Ryan Harris", "Ryan Sidebottom", "Ryan Ten Doeschate"],
    "datasets": [{
        "data": [56, 51, 47, 40, 40, 35, 25, 32, 22, 29, 26, 22, 20, 20, 16, 16, 14, 12, 13, 12, 12, 12, 10, 11, 11, 11, 9, 9, 8, 4, 7, 7, 3, 7, 5, 6, 4, 3, 6, 4, 5, 5, 3, 5, 5, 3, 4, 4, 4, 4, 3, 3, 3, 3, 2, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "backgroundColor": "rgba(54, 162, 235, 0.8)"
    }, {
        "data": [0, 0, 0, 1, 1, 0, 8, 1, 9, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 1, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "backgroundColor": "rgba(255, 99, 132, 0.8)"
    }]
};


var flags = {
    "Shane Warne": 1,
    "Sachin Tendulkar": 5,
    "Jacques Kallis": 4,
    "Adam Gilchrist": 1,
    "Brian Lara": 7,
    "Glenn McGrath": 1,
    "Alistair Cook": 2,
    "Kumar Sangakkara": 6,
    "Ricky Ponting": 1,
    "Wasim Akram": 3,
    "James Anderson": 2,
    "Muttiah Muralitharan": 6,
    "Mathew Hayden": 1,
    "AB De Villiers": 4,
    "Viv Richards": 7,
    "Dale Steyn": 4,
    "Andrew Flintoff": 2,
    "Virat Kohli": 5,
    "Curtly Ambrose": 7,
    "Hashim Amla": 4,
    "Malcolm Marshall": 7,
    "Mitchell Johnson": 1,
    "Joe Root": 2,
    "Garfield Sobers": 7,
    "Virender Sehwag": 5,
    "Stuart Broad": 2,
    "Graeme Swann": 2,
    "Kevin Pietersen": 2,
    "Marcus Trescothick": 2,
    "Steve Waugh": 1,
    "Shoaib Akhtar": 3,
    "Rahul Dravid": 5,
    "Imran Khan": 3,
    "Ben Stokes": 2,
    "Brendon McCullum": 9,
    "Ian Botham": 2,
    "Graeme Smith": 4,
    "MS Dhoni": 5,
    "Richard Hadlee": 9,
    "Mahela Jayawardene": 6,
    "Justin Langer": 1,
    "Gordon Greenidge": 7,
    "Graham Gooch": 2,
    "David Warner": 1,
    "Brett Lee": 1,
    "Chris Rogers": 1,
    "Chris Gayle": 7,
    "Dennis Lillee": 1,
    "Barry Richards": 4,
    "Waqar Younis": 3,
    "Sunil Gavaskar": 5,
    "Darren Gough": 2,
    "Darren Lehmann": 1,
    "Desmond Haynes": 7,
    "Don Bradman": 1,
    "Alan Knott": 2,
    "Aravinda De Silva": 6,
    "Charlotte Edwards": 2,
    "Allan Donald": 4,
    "Adam Voges": 1,
    "James Hildreth": 2,
    "Mitchell Starc": 1,
    "Meg Lanning": 1,
    "Michael Clarke": 1,
    "Murali Karthik": 5,
    "Shivnarine Chanderpaul": 7,
    "Rohit Sharma": 5,
    "Robert Key": 2,
    "Saeed Ajmal": 3,
    "Sam Robson": 1,
    "Morne Morkel": 4,
    "Mohammad Amir": 3,
    "Michael Holding": 7,
    "Jack Hobbs": 2,
    "Mark Ramprakash": 2,
    "Martin Crowe": 9,
    "Jos Buttler": 2,
    "Kagiso Rabada": 4,
    "Abdul Qadir": 3,
    "Andre Adams": 9,
    "Andrew Symonds": 1,
    "Andy Roberts": 7,
    "Anil Kumble": 5,
    "Cathryn Fitzpatrick": 2,
    "Chaminda Vaas": 6,
    "Chris Read": 2,
    "David Masters": 2,
    "Daniel Vettori": 9,
    "Harbhajan Singh": 5,
    "Ian Chappell": 1,
    "Ian Bell": 2,
    "Steve Harmison": 2,
    "Tim Murtagh": 8,
    "Vernon Philander": 4,
    "Yasir Arafat": 3,
    "Yasir Shah": 3,
    "Rangana Herath": 6,
    "Tim Southee": 9,
    "Trent Boult": 9,
    "Steven Davies": 2,
    "Wahab Riaz": 3,
    "Steve Smith": 1,
    "Stephen Fleming": 9,
    "Steve Finn": 2,
    "Tim Bresnan": 2,
    "Tim Linley": 2,
    "Ian Bishop": 7,
    "Inzamam-Ul_Haq": 3,
    "Ian Healy": 1,
    "Ian Shrubsole": 2,
    "Graham Napier": 2,
    "Graham Onions": 2,
    "Greg Chappell": 1,
    "H. D. Ackerman": 4,
    "Hanif Mohammad": 3,
    "Darren Stevens": 2,
    "David Hussey": 1,
    "Dwayne Leverock": 7,
    "Gary Ballance": 2,
    "Geoffry Boycott": 2,
    "Geraint Jones": 2,
    "Daien Martyn": 1,
    "Chris Woakes": 2,
    "Claire Taylor": 2,
    "Claude Henderson": 4,
    "Colin Cowdrey": 2,
    "Corey Collymore": 7,
    "Courtney Walsh": 7,
    "Chris Cairns": 9,
    "Andy Caddick": 2,
    "Andrew Strauss": 2,
    "Abdur Rehman": 3,
    "Adam Lyth": 2,
    "Adil Rashid": 2,
    "Akbar Ansari": 2,
    "Allan Border": 1,
    "Kane Williamson": 9,
    "Karen Bolton": 1,
    "Katherine Brunt": 2,
    "Lance Klusner": 4,
    "Lasith Malinga": 6,
    "Lisa Keightly": 2,
    "Josh Hazlewood": 1,
    "Joel Garnder": 7,
    "Javed Miandad": 3,
    "James Foster": 2,
    "Matt Prior": 2,
    "Matt Walker": 2,
    "Mark Ealham": 2,
    "Michael Hussey": 1,
    "Michael Slater": 1,
    "Michael Vaughan": 2,
    "Michael Di Venuto": 1,
    "Moeen Ali": 2,
    "Moises Henriques": 1,
    "Rashid Khan": 10,
    "Rashid Latif": 3,
    "Nathan Astle": 9,
    "Nick Browne": 2,
    "Owais Shah": 2,
    "Pat Cummins": 1,
    "Paul Nixon": 2,
    "Pragyan Ojha": 5,
    "Quinton De Kock": 4,
    "Saqlain Mushtaq": 2,
    "Sarah Taylor": 2,
    "Shane Bond": 9,
    "Shaun Pollock": 4,
    "Saeed Anwar": 3,
    "Ryan Harris": 1,
    "Ryan Sidebottom": 2,
    "Ryan Ten Doeschate": 4,
}